# This is the compute_cubic_traj srv file.
# The variables before the --- line are part of the request whereas the variables after are part of the rerponse.
# In the code, the cubic_traj_planner requests the service from compute_cubic_coeffs by providing the request parameters (p0, ..., tf) 
# In return the compute_cubic_coeffs returns the response variables (a0, ..., a3)


float32 p0
float32 pf
float32 v0
float32 vf
float32 t0
float32 tf
---
float32 a0
float32 a1
float32 a2
float32 a3